### ISSUE TITLE
1.7.8_coreos.0  points to a commit in a master branch

### ISSUE THREAD

**Issue by redbaron** [coreos/kubernetes#171]
Guys, what you are publishing as 1.7.8 is nowhere close to be a 1.7 kube. It is 7 days old master branch.

**Comment by redbaron** [comment]
Numbers tell for themselves
```
$ git diff v1.7.7 v1.7.7+coreos.0 --shortstat
 2 files changed, 3 insertions(+)

$ git diff v1.7.8 v1.7.8+coreos.0 --shortstat
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 2832 and retry the command.
 10874 files changed, 886997 insertions(+), 485052 deletions(-)
```

**Comment by squat** [comment]
Thanks for bringing this to my attention. This build occurred during the quay outage this week and something clearly went wrong when the build was repeated. I corrected the tag so that it points at the right commit now and I am re-running the image build. We are in the process of rewriting the automation for this process to remove any source of  human error.

**Comment by redbaron** [comment]
Thanks for a swift reaction and instantly pulling it out of quay.io

**Comment by redbaron** [comment]
@squat would you mind publishing it as `coreos.1` or `coreos.0+1` so that there is no chance that already pulles images remain in use by systems which pulled it already?

**Comment by squat** [comment]
@redbaron yes, I'm publishing coreos.1 now. Thanks again for the report.

**Comment by redbaron** [comment]
It is published as `coreos.0` :(

**Comment by squat** [comment]
There is another build running right now for `.1`.

**Comment by squat** [comment]
@redbaron, v1.7.8_coreos.1 is now live. Please use this tag going forward.
