### ISSUE TITLE
Evaluate adding rbd support to hyperkube image

### ISSUE THREAD

**Issue by aaronlevy** [coreos/kubernetes#68]
Related: https://github.com/coreos/coreos-kubernetes/issues/287

We should at least validate the "easy" options first, and then can determine our best option in the near term.

Initially I think this is:
- Add the user-space tools to the hyperkube image and test if this is enough for the kubernetes volumes to work
- Alternatively, check if we ship these tools with CoreOS, and potentially use the `--containerized` flag to make use of on-host mount tools.

/cc @robszumski @philips @pbx0

**Comment by peebs** [comment]
So just as I was trying to evangelize a crazy alternative to `--containerized` mjg59 stopped by and solved our problem through some remedial kernel education; We should definitely pursue option one as far as possible. There is no real reason why shipping these tools in the container won't work long-term since we ship no out-of-tree kernel modules and thus the userland ABI should be stable across any CoreOS release, even for these mount tools.

This is already true implicitly with CoreOS and maybe the OS should guarantee this explicitly since it would still be possible to break compatibility of userland tools through kernel configuration options. The last step is making sure these types of tools are exercised and tested as part of our OS release process. Sound right @mjg59?

Next step is testing option 1.

**Comment by peebs** [comment]
Done in https://github.com/coreos/kubernetes/pull/71
